CREATE TABLE CLIENTE(
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100)
);

CREATE TABLE PRODUTO(
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    DESCRICAO VARCHAR(100),
    PRECO_UNITARIO NUMERIC(20,2)
);

CREATE TABLE PEDIDO(
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    CLIENTE_ID BIGINT REFERENCES CLIENTE (ID),
    DATA_PEDIDO TIMESTAMP,
    TOTAL NUMERIC(20, 2)
);

CREATE TABLE ITEM_PEDIDO(
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    PEDIDO_ID BIGINT REFERENCES PEDIDO (ID),
    PRODUTO_ID BIGINT REFERENCES PRODUTO (ID),
    QUANTIDADE INTEGER
);